name: Basic-image-docker

on:
  push:
# Permite que el workflow se dispare cada vez que se pushee en la rama de main, ademas de incluir filtros
    branches:
      - main
# Estos filtros sirven para que el workflow se dispare si ha habido alguno cambio dentro de estas rutas.
    paths:
      - '.github/workflows/Basic-image-docker.yaml'
      - 'Docker-example/compose/**'
  pull_request:
    paths:
      - '.github/workflows/Basic-image-docker.yaml'
      - 'Docker-example/compose/**'
  workflow_dispatch:

# Permission: Los permisos que contiene el workflow

permissions:
  contents: read
  id-token: write

# Concurrency: Agrega la capacidad de solo ejecutar un unico run

concurrency:
  group: Basic-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  docker-build:
    runs-on: Ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show branch
        run: 'echo "Ref: ${{ github.ref }}"'

      - name: Validate Docker compose file
        run: docker compose -f Docker-example/compose/app-db-compose.yaml config

      - name: build app image
        run: docker compose -f Docker-example/compose/app-db-compose.yaml build

      - name: Start services
        run: docker compose -f Docker-example/compose/app-db-compose.yaml up -d

      - name: Show running containers
        run: docker compose -f Docker-example/compose/app-db-compose.yaml ps

      - name: wait for app health
        run: |
          for i in {1..20}; do
            if curl -fsS http://127.0.0.1:5000/health; then
              exit 0
            fi
            sleep 5
          done
          echo "App healthcheck failed"
          exit 1

      - name: Optional image scan
        run: 'echo "Aqui iria Trivy o similar"'

      - name: Show logs on failure
        if: failure()
        run: docker compose -f Docker-example/compose/app-db-compose.yaml logs

      - name: Cleanup
        if: always()
        run: docker compose -f Docker-example/compose/app-db-compose.yaml down -v